variable "project_name" {
  type        = string
  description = "Name of the Azure DevOps project"
}

variable "project_description" {
  type        = string
  description = "Description of the Azure DevOps project"
  default     = ""
}

variable "visibility" {
  type        = string
  description = "Visibility of the project (private or public)"
  default     = "private"
  validation {
    condition     = contains(["private", "public"], var.visibility)
    error_message = "Visibility must be either 'private' or 'public'."
  }
}

variable "work_item_template" {
  type        = string
  description = "Work item template to use (Agile, Basic, Scrum, CMMI)"
  default     = "Agile"
  validation {
    condition     = contains(["Agile", "Basic", "Scrum", "CMMI"], var.work_item_template)
    error_message = "Work item template must be one of: Agile, Basic, Scrum, CMMI."
  }
}

variable "features" {
  type        = map(string)
  description = "Map of Azure DevOps features to enable/disable"
  default = {
    "boards"       = "enabled"
    "repositories" = "enabled"
    "pipelines"    = "enabled"
    "testplans"    = "disabled"
  }
}

variable "azure_devops_pat" {
  type        = string
  sensitive   = true
  description = "Azure DevOps Personal Access Token for authentication"
}

variable "source_directory_app" {
  type        = string
  description = "Path to the directory containing files to push to the repository (empty string to skip)"
  default     = ""
}

variable "source_directory_charts" {
  type        = string
  description = "Path to the directory containing files to push to the repository (empty string to skip)"
  default     = ""
}

variable "source_directory_infra" {
  type        = string
  description = "Path to the directory containing files to push to the repository (empty string to skip)"
  default     = ""
}

variable "commit_message" {
  type        = string
  description = "Commit message for the initial push"
  default     = "Initial commit: Auto-generated by Terraform"
}

variable "force_push" {
  type        = bool
  description = "Force push on every terraform apply (uses timestamp trigger)"
  default     = false
}

variable "auto_generate_readme" {
  type        = bool
  description = "Automatically generate README.md if it doesn't exist"
  default     = true
}

variable "readme_content" {
  type        = string
  description = "Content for auto-generated README.md"
  default     = ""
}
