# Use the devops_project module to create project and repository
module "project" {
  source = "./modules/devops_project"

  project_name        = var.azure_devops_project
  project_description = var.azure_devops_project_description_infra
  azure_devops_pat    = var.azure_devops_pat

  visibility         = "private"
  work_item_template = "Agile"

  features = {
    "boards"       = "enabled"
    "repositories" = "enabled"
    "pipelines"    = "enabled"
    "testplans"    = "disabled"
  }

  # Push infra folder to the repository
  source_directory_infra  = "${path.module}/../infra"
  source_directory_charts = "${path.module}/../charts"
  source_directory_app    = "${path.module}/../app"

  commit_message = <<-EOT
    Initial commit: Azure Infrastructure Terraform configuration

    This configuration includes:
    - Azure Container Registry (ACR) setup
    - AKS cluster configuration
    - Nginx ingress controller
    - Cert-manager for Let's Encrypt SSL
    - Remote state backend configuration
    - Variable definitions and examples
    - Output definitions for infrastructure details
    - Azure DevOps pipeline configuration

    Auto-generated and pushed by Terraform bootstrap process.
  EOT

  readme_content = <<-EOT
    # Infrastructure as Code - Azure Container Registry & AKS

    This repository contains Terraform configuration for Azure infrastructure.

    ## Components

    - Azure Container Registry (ACR)
    - Azure Kubernetes Service (AKS)
    - Nginx Ingress Controller
    - Cert-Manager for SSL certificates

    ## Quick Start

    1. Configure variables:
       ```bash
       cp terraform.tfvars.example terraform.tfvars
       # Edit terraform.tfvars with your settings
       ```

    2. Initialize and deploy:
       ```bash
       terraform init
       terraform apply
       ```

    ## Backend Configuration

    The `backend.tf` file is auto-generated by the bootstrap process and configures remote state storage in Azure Blob Storage.

    ## Files

    - `main.tf` - Main Terraform configuration
    - `variables.tf` - Variable definitions
    - `outputs.tf` - Output values
    - `backend.tf` - Backend configuration (auto-generated)
    - `terraform.tfvars.example` - Example configuration
    - `ingress.tf` - Ingress controller configuration
    - `certmanager.tf` - Certificate manager configuration

    ## Documentation

    For detailed information, see the included documentation files:
    - `README.md` - This file
    - `AKS_SETUP.md` - AKS cluster setup guide
    - `QUICK_START.md` - Quick start guide
    - `PIPELINE_SETUP.md` - Pipeline configuration guide

    ---
    © 2025 Serhii Nesterenko
  EOT

  force_push = var.force_push
}

# Create Azure DevOps build pipeline for infrastructure deployment
resource "azuredevops_build_definition" "infra_pipeline" {
  project_id      = module.project.project_id
  name            = "Infrastructure Deploy"
  agent_pool_name = "Default"

  repository {
    repo_type   = "TfsGit"
    repo_id     = module.project.repository_infra_id
    branch_name = "refs/heads/master"
    yml_path    = "pipelines/deploy.yml"
  }

  ci_trigger {
    use_yaml = true
  }

  variable {
    name  = "TF_STATE_RESOURCE_GROUP"
    value = azurerm_resource_group.bootstrap.name
  }

  variable {
    name  = "TF_STATE_STORAGE_ACCOUNT"
    value = azurerm_storage_account.tfstate.name
  }

  variable {
    name  = "TF_STATE_CONTAINER_NAME"
    value = azurerm_storage_container.tfstate.name
  }

  variable {
    name  = "TF_STATE_KEY"
    value = "${var.azure_devops_project}.tfstate"
  }

  variable {
    name  = "AZDO_PERSONAL_ACCESS_TOKEN"
    secret_value = var.azure_devops_pat
    is_secret = true
  }

  variable {
    name  = "AZDO_ORG_SERVICE_URL"
    value = var.azure_devops_org_url
  }

}

# Create Azure DevOps build pipeline for infrastructure destruction
resource "azuredevops_build_definition" "infra_pipeline_destroy" {
  project_id      = module.project.project_id
  name            = "Infrastructure Destroy"
  agent_pool_name = "Default"

  repository {
    repo_type   = "TfsGit"
    repo_id     = module.project.repository_infra_id
    branch_name = "refs/heads/master"
    yml_path    = "pipelines/destroy.yml"
  }

  ci_trigger {
    use_yaml = true
  }

  variable {
    name  = "TF_STATE_RESOURCE_GROUP"
    value = azurerm_resource_group.bootstrap.name
  }

  variable {
    name  = "TF_STATE_STORAGE_ACCOUNT"
    value = azurerm_storage_account.tfstate.name
  }

  variable {
    name  = "TF_STATE_CONTAINER_NAME"
    value = azurerm_storage_container.tfstate.name
  }

  variable {
    name  = "TF_STATE_KEY"
    value = "${var.azure_devops_project}.tfstate"
  }

  variable {
    name  = "AZDO_PERSONAL_ACCESS_TOKEN"
    secret_value = var.azure_devops_pat
    is_secret = true
  }

  variable {
    name  = "AZDO_ORG_SERVICE_URL"
    value = var.azure_devops_org_url
  }

}

# Create Azure DevOps build pipeline for charts
resource "azuredevops_build_definition" "app_charts" {
  project_id      = module.project.project_id
  name            = "Charts Build And Publish"
  agent_pool_name = "Default"

  build_completion_trigger {
    build_definition_id = azuredevops_build_definition.infra_pipeline.id
    branch_filter {
      include = ["refs/heads/master"]
    }
  }

  repository {
    repo_type   = "TfsGit"
    repo_id     = module.project.repository_app_id
    branch_name = "refs/heads/master"
    yml_path    = "pipelines/azure-pipelines.yaml"
  }

  ci_trigger {
    use_yaml = true
  }

}

# Create Azure DevOps build pipeline for app deployment
resource "azuredevops_build_definition" "app_pipeline" {
  project_id      = module.project.project_id
  name            = "App Deploy"
  agent_pool_name = "Default"

  build_completion_trigger {
    build_definition_id = azuredevops_build_definition.infra_pipeline.id
    branch_filter {
      include = ["refs/heads/master"]
    }
  }

  repository {
    repo_type   = "TfsGit"
    repo_id     = module.project.repository_app_id
    branch_name = "refs/heads/master"
    yml_path    = "pipelines/azure-pipelines.yaml"
  }

  ci_trigger {
    use_yaml = true
  }

}

# Authorize service connection for the pipelines
resource "azuredevops_pipeline_authorization" "arm_auth" {
  project_id  = module.project.project_id
  resource_id = azuredevops_serviceendpoint_azurerm.azure_connection.id
  pipeline_id = azuredevops_build_definition.infra_pipeline.id
  type        = "endpoint"
}

# Authorize Azure service connection for infrastructure destroy pipeline
resource "azuredevops_pipeline_authorization" "arm_auth_destroy" {
  project_id  = module.project.project_id
  resource_id = azuredevops_serviceendpoint_azurerm.azure_connection.id
  pipeline_id = azuredevops_build_definition.infra_pipeline_destroy.id
  type        = "endpoint"
}



