#!/bin/bash

set -e

echo "================================================"
echo "Pushing files to Azure DevOps repository"
echo "================================================"

# Configuration from environment variables
REPO_URL="${REPO_URL}"
PAT="${AZURE_DEVOPS_PAT}"
SOURCE_DIR="${SOURCE_DIR}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-Initial commit: Auto-generated by Terraform}"

if [ -z "$REPO_URL" ] || [ -z "$PAT" ]; then
    echo "ERROR: Required environment variables not set"
    echo "Required: REPO_URL, AZURE_DEVOPS_PAT"
    exit 1
fi

if [ -z "$SOURCE_DIR" ]; then
    echo "ERROR: SOURCE_DIR environment variable not set"
    exit 1
fi

# Resolve absolute path for source directory
SOURCE_DIR=$(readlink -f "$SOURCE_DIR")

if [ ! -d "$SOURCE_DIR" ]; then
    echo "ERROR: Source directory not found at: $SOURCE_DIR"
    exit 1
fi

echo "Source directory: $SOURCE_DIR"

# Create temporary directory for git operations
TEMP_DIR=$(mktemp -d)
echo "Created temporary directory: $TEMP_DIR"

# Cleanup function
cleanup() {
    echo "Cleaning up temporary directory..."
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

# Navigate to temp directory
cd "$TEMP_DIR"

# Configure git credentials for Azure DevOps
echo "Configuring git credentials..."
git config --global credential.helper store
echo "https://oauth:${PAT}@dev.azure.com" > ~/.git-credentials

# Clone the empty repository
echo "Cloning repository: $REPO_URL"
git clone "$REPO_URL" repo || {
    echo "ERROR: Failed to clone repository"
    exit 1
}

# Clean all existing files except .git directory
echo "Cleaning existing repository contents..."
find repo -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} \;
cd repo

# Configure git user
git config user.email "terraform@automation.local"
git config user.name "Terraform Automation"

# Copy files from source directory to the repository
echo "Copying files from source directory..."
cp -r "$SOURCE_DIR"/. . 2>/dev/null || {
    echo "WARNING: No files found in source directory or copy failed"
}

# Check if there are any changes to commit
if [ -z "$(git status --porcelain)" ]; then
    echo "No changes to commit. Repository is up to date."
    exit 0
fi

# Add all files (including deletions)
echo "Adding files to git..."
git add -A

# Commit changes
echo "Committing changes..."
git commit -m "$COMMIT_MESSAGE"

# Push to main/master branch
echo "Pushing to remote repository..."
git push origin HEAD:refs/heads/master 2>/dev/null || {
    echo "ERROR: Failed to push to repository"
    exit 1
}

echo "================================================"
echo "Successfully pushed files to Azure DevOps repository!"
echo "Repository: $REPO_URL"
echo "================================================"
