{
 "title": "Overall status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Response time (90% quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "demo_http_response_time_seconds{quantile='0.9',method='GET',status='200'}",
     "legendFormat": "{{ ipv4 }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "sum(rate(demo_http_response_count_total[1m])) by (ipv4)",
     "legendFormat": "{{ ipv4 }}"
    }
   ]
  },
  {
   "title": "Status codes per second != 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "sum(rate(demo_http_response_count_total{status!='200'}[1m])) by (status)",
     "legendFormat": "{{ ipv4 }}"
    }
   ]
  },
  {
   "title": "HTTP traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(demo_http_response_size_bytes[1m])) by (ipv4)",
     "legendFormat": "{{ ipv4 }}"
    }
   ]
  },
  {
   "title": "Running workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    { "expr": "sum(up{job='worker'})", "legendFormat": "{{ ipv4 }}" }
   ]
  },
  {
   "title": "Running containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers{state='running'}) by (ipv4)-5",
     "legendFormat": "{{ ipv4 }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode='idle'}[1m])) by (ipv4) * 100)",
     "legendFormat": "{{ ipv4 }}"
    }
   ]
  },
  {
   "title": "Load per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "(sum(rate(demo_http_response_count_total[1m])) by (ipv4))/(sum(engine_daemon_container_states_containers{state='running'}-5) by (ipv4))",
     "legendFormat": "{{ ipv4 }}"
    }
   ]
  }
 ]
}