{
 "title": "Nginx Balancer",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "sum(rate(demo_http_response_time_seconds_sum[5m])) by (instance) / sum(rate(demo_http_response_time_seconds_count[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "targets": [
    {
     "expr": "sum(rate(demo_http_response_time_seconds_count[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Response time (90% quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "demo_http_response_time_seconds{quantile='0.9',method='GET',status='200'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(demo_http_response_size_bytes[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "sum(rate(demo_http_response_count_total[10m])) by (status)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}